language : node_js
node_js :
 - stable
install:
 - npm install
jobs:
  include:
    - name: Test
      script: npm run test
    - name: Lint
      script: npm run lint
    - name: Size
      script: npm run size
